# Generated by Django 3.0.2 on 2020-01-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('LisenceNumber', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=50, null=True)),
                ('carmodel', models.CharField(max_length=50, null=True)),
                ('coordinates', models.CharField(max_length=50)),
            ],
        ),
    ]
