# Generated by Django 3.0.2 on 2020-01-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotemodel',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='annotemodel',
            name='filename',
            field=models.CharField(default='image.jpg', max_length=50),
        ),
        migrations.AddField(
            model_name='annotemodel',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotemodel',
            name='shape',
            field=models.CharField(default='rect', max_length=30),
        ),
        migrations.AddField(
            model_name='annotemodel',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotemodel',
            name='xcoordinate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotemodel',
            name='ycoordinate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='annotemodel',
            name='LisenceNumber',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='annotemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
