# Generated by Django 2.2.2 on 2020-02-07 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annote', '0002_auto_20200113_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotemodel',
            name='LisenceNumber',
        ),
        migrations.RemoveField(
            model_name='annotemodel',
            name='carmodel',
        ),
        migrations.RemoveField(
            model_name='annotemodel',
            name='company',
        ),
    ]
