# Generated by Django 2.2.2 on 2020-02-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annote', '0004_remove_annotemodel_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotemodel',
            name='attribute',
            field=models.CharField(default='trash', max_length=30),
        ),
    ]
